name: Build Docker Image

on:
  push:
    branches:
      - main  # Ali katera koli druga veja, ki jo želite spremljati

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-image -f C:/Users/benja/Desktop/Stuff/Šola/Strojno\ ucenje2\ /dockerfile .


